### PR TITLE
Update to Django 2

### PR DESCRIPTION
**Pull request by larsrinn**
Hey,

I merged the current head of pydanny/master into your fork and resolved the merge conflicts.

Some things I'm not too sure about:
* Why did you drop `django-allauth` for the react version?
* Forms and Views from the example application could be deleted. Should we rather write some example Django components that basically do the same things and can act as a guidance on how to use the integration?

If you think something else should be done before merging, let me know. I'll be happy to help out

### CODE REVIEW

**Comment by genomics-geek** [comment]
Awesome. Thanks a lot!

**Comment by yeungbri** [comment]
Sorry if this comes off rude, but is there an ETA on when this will be reviewed and merged?

**Comment by Afrowave** [comment]
Done. Thank you @larsrinn for the good work.

**Comment by genomics-geek** [comment]
@larsrinn, @yeungbri, @Afrowave  - There is a [new branch](https://github.com/chopdgd/cookiecutter-django-reactjs/tree/feature-create-react-app) that does not require create-react-app eject.  This would be *MUCH* easier to maintain IMO.  I have recently switched all of my projects to this layout to leverage Facebook's constant improvements and maintain webpack :).

Let me know what you guys think :)

**Comment by genomics-geek** [comment]
Also updated everything from pydanny's main branch, so should be up to date and support Django 2

**Pull request merged**
